Add signing job

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,6 +7,7 @@ on:
         description: 'Version'
         required: true
         type: string
+      # We use SemVer, anything before v1.0.0 is a pre-release, but this could also include versions like v1.1.0-beta.
       prerelease:
         description: 'Prerelease'
         required: true
@@ -14,8 +15,16 @@ on:
         type: boolean
 
 jobs:
+  validate:
+    runs-on: ubuntu-latest
+    steps:
+    # Special request from @kyle-rader, so no one can accidentally omit a 'v'.
+    - name: Validate version
+      run: echo ${{ github.event.inputs.version }} | grep 'v.*' || (echo "Version must start with a v (e.g., v0.1.0)"; false)
+
   build:
     runs-on: ${{ matrix.os }}
+    needs: [validate]
     strategy:
       matrix:
         # We build on Linux, but don't yet ship Linux because we can't easily sign those releases.
@@ -48,11 +57,85 @@ jobs:
         name: azureauth-${{ github.event.inputs.version }}-${{ matrix.runtime }}
         path: dist/${{ matrix.runtime }}
 
-  # TODO: We need a signing step before packaging...
+  sign:
+    # This step has to run on Windows because ESRPClient.exe is currently only availabe for that platform.
+    runs-on: windows-latest
+    needs: [build]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Setup Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: '3.10'
+      - name: Setup NuGet
+        uses: NuGet/setup-nuget@v1
+        with:
+          nuget-version: '5.x'
+      - name: Download ESRPClient.exe
+        env:
+          ESRP_VERSION: ${{ secrets.ESRP_VERSION }}
+          NUGET_CREDENTIALS: ${{ secrets.NUGET_CREDENTIALS }}
+        run: |
+          nuget sources add -Name esrp -Username esrp-downloader -Password $env:NUGET_CREDENTIALS -Source https://microsoft.pkgs.visualstudio.com/_packaging/ESRP/nuget/v3/index.json
+          nuget install Microsoft.EsrpClient -Version "$env:ESRP_VERSION" -OutputDirectory .\esrp -Source https://microsoft.pkgs.visualstudio.com/_packaging/ESRP/nuget/v3/index.json
+      - name: Login to Azure
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+      # We need these certificates installed so that we can run ESRPClient.exe.
+      - name: Install certificates
+        env:
+          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
+          AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
+          ESRP_AAD_CERT_NAME: ${{ secrets.AZURE_VAULT_ESRP_AAD_CERT_NAME }}
+          ESRP_AAD_CERT_VERSION: ${{ secrets.AZURE_VAULT_ESRP_AAD_CERT_VERSION }}
+          ESRP_REQ_CERT_NAME: ${{ secrets.AZURE_VAULT_ESRP_REQ_CERT_NAME }}
+          ESRP_REQ_CERT_VERSION: ${{ secrets.AZURE_VAULT_ESRP_REQ_CERT_VERSION }}
+        run: |
+          az keyvault secret download --subscription "$env:AZURE_SUBSCRIPTION" --vault-name "$env:AZURE_VAULT" --name "$env:ESRP_AAD_CERT_NAME" --version "$env:ESRP_AAD_CERT_VERSION" -f cert.pfx
+          certutil -f -importpfx cert.pfx
+          Remove-Item cert.pfx
 
+          az keyvault secret download --subscription "$env:AZURE_SUBSCRIPTION" --vault-name "$env:AZURE_VAULT" --name "$env:ESRP_REQ_CERT_NAME" --version "$env:ESRP_REQ_CERT_VERSION" -f cert.pfx
+          certutil -f -importpfx cert.pfx
+          Remove-Item cert.pfx
+      # We download all artifacts and overwrite them with signed files, but only upload ones which we can properly sign.
+      - name: Download all artifacts
+        uses: actions/download-artifact@v3
+      - name: Sign artifacts
+        env:
+          SIGNING_AAD_ID: ${{ secrets.SIGNING_AAD_ID }}
+          SIGNING_TENANT_ID: ${{ secrets.SIGNING_TENANT_ID }}
+          SIGNING_KEY_CODE_AUTHENTICODE: ${{ secrets.SIGNING_KEY_CODE_AUTHENTICODE }}
+          SIGNING_KEY_CODE_MAC: ${{ secrets.SIGNING_KEY_CODE_MAC }}
+          SIGNING_CUSTOMER_CORRELATION_ID: ${{ secrets.SIGNING_CUSTOMER_CORRELATION_ID }}
+          ESRP_CLIENT_EXE: ".\\esrp\\Microsoft.EsrpClient.${{ secrets.ESRP_VERSION }}\\tools\\EsrpClient.exe"
+        # We might be able to speed/clean up this job by using another matrix strategy.
+        run: |
+          python .\bin\sign.py "$env:ESRP_CLIENT_EXE" --runtime=win10-x64 --source=azureauth-${{ github.event.inputs.version }}-win10-x64
+          python .\bin\sign.py "$env:ESRP_CLIENT_EXE" --runtime=osx-x64 --source=azureauth-${{ github.event.inputs.version }}-osx-x64
+          python .\bin\sign.py "$env:ESRP_CLIENT_EXE" --runtime=osx-arm64 --source=azureauth-${{ github.event.inputs.version }}-osx-arm64
+      - name: Upload signed win10-x64 artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: azureauth-${{ github.event.inputs.version }}-win10-x64
+          path: azureauth-${{ github.event.inputs.version }}-win10-x64
+      - name: Upload signed osx-x64 artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: azureauth-${{ github.event.inputs.version }}-osx-x64
+          path: azureauth-${{ github.event.inputs.version }}-osx-x64
+      - name: Upload signed osx-arm64 artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: azureauth-${{ github.event.inputs.version }}-osx-arm64
+          path: azureauth-${{ github.event.inputs.version }}-osx-arm64
+
+  # Currently we package artifacts into the most commonly accessible archive format for their respective platforms.
   package:
     runs-on: ubuntu-latest
-    needs: build
+    needs: [sign]
     steps:
     - name: Download all artifacts
       uses: actions/download-artifact@v3
